Added dutch translations
Soullivaneuh/IsoCodesValidator pull request #145
Opened 2021-06-25 08:19 UTC by ikulis

Added dutch translations.

2021-06-28 12:32 UTC, sstok requested changes
Some minor typo's. but overall looks good.

2021-06-28 12:32 UTC, sstok commented on src/translations/validators.nl.xlf
> +                <target>Deze waarde is geen geldig credit card nummer .</target>
```suggestion
                <target>Deze waarde is geen geldig credit card nummer.</target>
```

2021-06-28 12:32 UTC, sstok commented on src/translations/validators.nl.xlf
> +                <target>Deze waarde is geen geldig  telefoonnummer.</target>
```suggestion
                <target>Deze waarde is geen geldig telefoonnummer.</target>
```

2021-06-28 18:51 UTC, sstok approved these changes

2021-07-16 11:31 UTC, ikulis commented
@sstok Hi, any change it can be released?

2021-07-17 09:02 UTC, sstok commented
I am not a maintainer 😄 🤷🏼‍♂️

2021-07-18 07:43 UTC, ikulis commented
@soullivaneuh Hi, any chance this pr can be released?

2023-01-20 22:38 UTC, husseinlashin commented
G

2023-09-19 12:40 UTC, merged

2023-09-19 12:42 UTC, soullivaneuh commented
@ikulis Merged and released: https://github.com/soullivaneuh/IsoCodesValidator/releases/tag/v4.2.0

Thanks for the contribution and sorry for the big delay!